### ISSUE TITLE
Error with the PropSymbolsLayer function

### ISSUE THREAD

**Issue by kguilaume** [riatelab/cartography#40] opened 2018-01-10 10:32 UTC
Good morning,

When I use the PropSymbolsLayer function with the spdf and df parameters (instead of x parameter), I obtain the following error code :

> Error: In ‘udunits_from_proj[x$units]’, ‘udunits_from_proj’ and ‘x’ are not recognized by udunits.
> See a table of valid unit symbols and names with valid_udunits().
> Add custom user-defined units with install_symbolic_unit().

By the way, the corresponding code in the R documentation Platform does not work in my laptop : 
## Example 2
data("nuts2006")
# Countries plot
plot(nuts0.spdf, col = "grey60",border = "grey20")
# Population plot on proportional symbols
propSymbolsLayer(spdf = nuts0.spdf, df = nuts0.df,
                 var = "gdppps2008",
                 symbols = "bar", col =  "#B00EF0",
                 legend.pos = "right",
                 legend.title.txt = "GDP\nin Millions PPS (2008)",
                 legend.style = "e")

I got the same error message.

Is someone can help me?
Thanks a lot.

Kevin

**Comment by kguilaume** [comment] 2018-01-10 12:33
Thanks. The result of sessionInfo() is :

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cartography_2.0.2 sf_0.5-5          rgeos_0.3-26      rgdal_1.2-16      classInt_0.1-24   plotrix_3.7       sp_1.2-5         

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12    magrittr_1.5    units_0.5-1     xtable_1.8-2    lattice_0.20-35 R6_2.2.2        udunits2_0.13   tools_3.4.1     grid_3.4.1     
[10] e1071_1.6-8     DBI_0.7         htmltools_0.3.6 crosstalk_1.0.0 class_7.3-14    leaflet_1.1.0   digest_0.6.12   shiny_1.0.5     htmlwidgets_0.9
[19] mime_0.5        compiler_3.4.1  httpuv_1.3.5

**Comment by rCarto** [comment] 2018-01-10 13:52
I was unable to reproduce the error. You can try to update `sf`, `sp` and R itself.

**Comment by kguilaume** [comment] 2018-01-11 13:14
Ok thanks for trying. What is your R version? Perhaps, the packages are not compatible with the version of my R.

**Comment by rCarto** [comment] 2018-01-30 10:20
cartography should work with R version >= 3.3.0. Have you managed to make it work? Can I close the issue?

**Comment by kguilaume** [comment] 2018-01-31 16:32
Hello,

Apparently, it works on the laptop of my colleagues. You should be right.
You can close the issue.
Sorry for the delay.
Thanks

Kevin

2018-01-30 11:20 GMT+01:00 Timothée Giraud <notifications@github.com>:

**Closed** 2018-02-01 08:43 UTC
